services:
  #web:
  #  build: .
  #  ports:
  #    - "80:8000"
  #  depends_on:
  #    db:
  #      condition: service_healthy
  #  command: ["python", "app.py"]
 
  db:
      image: postgres
      restart: always
      environment:
        POSTGRES_DB: "pgdb"
        POSTGRES_USER: "pguser"
        POSTGRES_PASSWORD: "fr2Yitl4BgX"
      ports:
        - "5432:5432"
      volumes:
      - pgdata:/var/lib/postgresql/data
      #healthcheck:
      #  test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      #  interval    : 1s
      #  timeout: 5s
      #  retries: 10
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  pgdata: